### ISSUE TITLE
window PoSt modelling and test cases

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-scheduling#26]
We need to minimize the likelyhood of tasks such as PoSt missing their deadlines

- [x] create integration tests for these situation (requests arriving at the worst time, etc.)
- [ ] Solution1: allow a configuration setting to "PIN" task groups to specific exclusive resources. Like "group: PoSt" has exclusive access to "/opencl/gpu/0"
- [x] Solution2: preemption

**Comment by jleni** [comment]
Depends on #19 #17

**Comment by neithanmo** [comment]
The issues this task depends on are closed now. Can we close this??

**Comment by leongb** [comment]
Yep this is indeed fixed!
