### ISSUE TITLE
Handle panics in scheduler/solver 

### ISSUE THREAD

**Issue by neithanmo** [Zondax/filecoin-scheduling#63]
If the scheduler panics, the RPC service remains running or is closed ungratefully.

**Comment by jleni** [comment]
@neithanmo Is this still open and applicable?
I would prefer to:
- Log
- Close gracefully
- a client will instantiate another instance

**Comment by neithanmo** [comment]
this is kind of done by the tokio runtime.  later if we want to implement a stateful version of the scheduler we can open this again, but maybe this won't be necessary as it can be done in a separate thread called maintenance which will save regular snapshots of the scheduler state.
