### ISSUE TITLE
Integration into Neptune

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-scheduling#84]

**Comment by neithanmo** [comment]
almost finished.
https://github.com/filecoin-project/neptune/pull/89

**Comment by neithanmo** [comment]
the work in ilecoin-project/neptune#89  was moved to https://github.com/filecoin-project/neptune/pull/93

**Comment by neithanmo** [comment]
we can consider this also done, so Neptune does not include the scheduler but a refactor in order to fit better into the scheduler control-flow mechanism.
