### ISSUE TITLE
Integration into rust-fil-proofs

### ISSUE THREAD

**Issue by neithanmo** [Zondax/filecoin-scheduling#86]
- [ ] bellperson-rustfilproofs
- [x] scheduler
- [x] neptune

**Comment by jleni** [comment]
bellperson-rustfilproofs is missing a way to communicate the task type / deadline to the GPU calculation

**Comment by neithanmo** [comment]
we can close this as there is a full-functional integration, this might change as the testing moves forward, and be redesigned but this would be out of scope for this milestone.
